### PR TITLE
Issue 136 graceful error

### LINKED ISSUE #136: graceful error and exit if no authn creds found
## Description

I usually use environment variables for my appgate auth creds, i forgot this time and it panics the provider. could use a proper catch / error message for clarity

### Terraform CLI, Terraform appgatesdp Provider Version, and Appgate Appliance version(s)

```
terraform -v
Terraform v1.0.0
on darwin_amd64
+ provider registry.terraform.io/appgate/appgatesdp v0.6.0
```
appgate appliance version: 5.4.1

### Affected Resource(s)

* all provider

### Panic Output

```
panic: interface conversion: interface {} is nil, not *appgate.Client

goroutine 40 [running]:
github.com/appgate/terraform-provider-appgatesdp/appgate.dataSourceAppgateSiteRead(0xc000666a80, 0x0, 0x0, 0x26e99d0, 0xc00039c900)
	github.com/appgate/terraform-provider-appgatesdp/appgate/data_source_appgate_site.go:59 +0x4c7
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc00031a540, 0x2028fa8, 0xc0005cc080, 0xc000666a80, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/resource.go:335 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc00031a540, 0x2028fa8, 0xc0005cc080, 0xc0004de9e0, 0x0, 0x0, 0x0, 0xc0004de9e0, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/resource.go:558 +0xfd
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc00030a840, 0x2028fa8, 0xc0005cc080, 0xc0004de8a0, 0xc0005cc080, 0x100b665, 0x1dc4740)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/grpc_provider.go:1105 +0x4d6
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadDataSource(0xc000678da0, 0x2029050, 0xc0005cc080, 0xc0004cc550, 0xc000678da0, 0xc0004aca20, 0xc0003d9ba0)
	github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:247 +0xe5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler(0x1e133c0, 0xc000678da0, 0x2029050, 0xc0004aca20, 0xc000300a20, 0x0, 0x2029050, 0xc0004aca20, 0xc000534150, 0x62)
	github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:416 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000331500, 0x2031db8, 0xc000399080, 0xc000396300, 0xc000381a70, 0x26aa5f0, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000331500, 0x2031db8, 0xc000399080, 0xc000396300, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00030c2b0, 0xc000331500, 0x2031db8, 0xc000399080, 0xc000396300)
	google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-appgatesdp_v0.6.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
╷
│ Error: Plugin did not respond
│
│   with data.appgatesdp_site.acme,
│   on data.tf line 12, in data "appgatesdp_site" "acme":
│   12: data "appgatesdp_site" "acme" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more details.
```

### PR DESCRIPTION
**Pull request by danijeel**
This PR fixes #136 , cherry picked and test with #137 for better support within terraform >= 1.0.0

<details>

tested on "5.4.2-25318-beta"
```bash
> tf version
Terraform v1.0.1
on linux_amd64

Your version of Terraform is out of date! The latest version
is 1.0.2. You can update by downloading from https://www.terraform.io/downloads.html
~/dev/terraform-provider-appgatesdp on issue-136-graceful-error ✔                                                                                                                                                [3ee50bf]  10:28
> make testacc
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./appgate -v -count 1 -parallel 20  -timeout 120m
=== RUN   TestNewClient
--- PASS: TestNewClient (0.00s)
=== RUN   TestLoginInternalServerError
--- PASS: TestLoginInternalServerError (0.00s)
=== RUN   TestConfig
=== RUN   TestConfig/test_before_5.4
=== RUN   TestConfig/test_5.4_login
=== RUN   TestConfig/invalid_client_version
--- PASS: TestConfig (0.01s)
    --- PASS: TestConfig/test_before_5.4 (0.00s)
    --- PASS: TestConfig/test_5.4_login (0.00s)
    --- PASS: TestConfig/invalid_client_version (0.01s)
=== RUN   TestAccAppgateAdministrativeRoleDataSource
=== PAUSE TestAccAppgateAdministrativeRoleDataSource
=== RUN   TestAccAppgateApplianceCustomizationDataSource
=== PAUSE TestAccAppgateApplianceCustomizationDataSource
=== RUN   TestAccAppgateApplianceSeedDataSource
--- PASS: TestAccAppgateApplianceSeedDataSource (10.34s)
=== RUN   TestAccAppgateCADataSource
--- PASS: TestAccAppgateCADataSource (2.64s)
=== RUN   TestAccAppgateGlobalSettingsDataSource
--- PASS: TestAccAppgateGlobalSettingsDataSource (2.77s)
=== RUN   TestAccAppgateIdentityProviderDataSource
--- PASS: TestAccAppgateIdentityProviderDataSource (2.65s)
=== RUN   TestAccAppgateIPPoolDataSource
--- PASS: TestAccAppgateIPPoolDataSource (4.38s)
=== RUN   TestAccAppgateLocalUserDataSource
--- PASS: TestAccAppgateLocalUserDataSource (3.42s)
=== RUN   TestAccAppgateMfaProviderDataSource
=== PAUSE TestAccAppgateMfaProviderDataSource
=== RUN   TestAccAppgateTrustedCertificateDataSource
=== PAUSE TestAccAppgateTrustedCertificateDataSource
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestAccadministrativeRoleBasic
=== PAUSE TestAccadministrativeRoleBasic
=== RUN   TestAccadministrativeRoleWithScope
=== PAUSE TestAccadministrativeRoleWithScope
=== RUN   TestAccadministrativeMultiplePrivilegesValidation
=== PAUSE TestAccadministrativeMultiplePrivilegesValidation
=== RUN   TestAccadministrativeMultiplePrivilegesValidation52
=== PAUSE TestAccadministrativeMultiplePrivilegesValidation52
=== RUN   TestAccApplianceCustomizationBasic
=== PAUSE TestAccApplianceCustomizationBasic
=== RUN   TestAccApplianceBasicController
=== PAUSE TestAccApplianceBasicController
=== RUN   TestAccApplianceConnector
=== PAUSE TestAccApplianceConnector
=== RUN   TestAccApplianceBasicGateway
=== PAUSE TestAccApplianceBasicGateway
=== RUN   TestAccApplianceBasicControllerWithoutOverrideSPA
=== PAUSE TestAccApplianceBasicControllerWithoutOverrideSPA
=== RUN   TestAccApplianceBasicControllerOverriderSPADisabled
=== PAUSE TestAccApplianceBasicControllerOverriderSPADisabled
=== RUN   TestAccAppliancePortalSetup
=== PAUSE TestAccAppliancePortalSetup
=== RUN   TestAccBlacklistUserBasic
=== PAUSE TestAccBlacklistUserBasic
=== RUN   TestAccClientConnectionsBasic
--- PASS: TestAccClientConnectionsBasic (3.86s)
=== RUN   TestAccClientProfileBasic
=== PAUSE TestAccClientProfileBasic
=== RUN   TestAccConditionBasic
=== PAUSE TestAccConditionBasic
=== RUN   TestAccCriteriaScriptBasic
=== PAUSE TestAccCriteriaScriptBasic
=== RUN   TestAccDeviceScriptBasic
=== PAUSE TestAccDeviceScriptBasic
=== RUN   TestAccEntitlementScriptBasic
=== PAUSE TestAccEntitlementScriptBasic
=== RUN   TestAccEntitlementBasicPing
=== PAUSE TestAccEntitlementBasicPing
=== RUN   TestAccEntitlementBasicWithMonitor
=== PAUSE TestAccEntitlementBasicWithMonitor
=== RUN   TestAccEntitlementUpdateActionOrder
=== PAUSE TestAccEntitlementUpdateActionOrder
=== RUN   TestAccEntitlementUpdateActionHostOrder
=== PAUSE TestAccEntitlementUpdateActionHostOrder
=== RUN   TestAccEntitlementUpdateActionPortsSetOrder
=== PAUSE TestAccEntitlementUpdateActionPortsSetOrder
=== RUN   TestAccGlobalSettingsBasic
=== PAUSE TestAccGlobalSettingsBasic
=== RUN   TestAccConnectorIdentityProviderBasic
--- PASS: TestAccConnectorIdentityProviderBasic (4.11s)
=== RUN   TestAccLdapCertificateIdentityProvidervBasic
=== PAUSE TestAccLdapCertificateIdentityProvidervBasic
=== RUN   TestAccLdapIdentityProviderBasic
=== PAUSE TestAccLdapIdentityProviderBasic
=== RUN   TestAccLocalDatabaseIdentityProviderBasic
--- PASS: TestAccLocalDatabaseIdentityProviderBasic (4.14s)
=== RUN   TestAccRadiusIdentityProviderBasic
=== PAUSE TestAccRadiusIdentityProviderBasic
=== RUN   TestAccSamlIdentityProviderBasic
=== PAUSE TestAccSamlIdentityProviderBasic
=== RUN   TestAccIPPoolBasic
=== PAUSE TestAccIPPoolBasic
=== RUN   TestAccLocalUserBasic
=== PAUSE TestAccLocalUserBasic
=== RUN   TestAccMfaProviderBasic
=== PAUSE TestAccMfaProviderBasic
=== RUN   TestAccAdminMfaSettingsBasic
=== PAUSE TestAccAdminMfaSettingsBasic
=== RUN   TestAccPolicyBasic
=== PAUSE TestAccPolicyBasic
=== RUN   TestAccRingfenceRuleBasicICMP
=== PAUSE TestAccRingfenceRuleBasicICMP
=== RUN   TestAccRingfenceRuleBasicTCP
=== PAUSE TestAccRingfenceRuleBasicTCP
=== RUN   TestAccSiteBasic
=== PAUSE TestAccSiteBasic
=== RUN   TestAccSiteBasicAwsResolverWithoutSecret
=== PAUSE TestAccSiteBasicAwsResolverWithoutSecret
=== RUN   TestAccTrustedCertificateBasic
=== PAUSE TestAccTrustedCertificateBasic
=== CONT  TestAccAppgateAdministrativeRoleDataSource
=== CONT  TestAccEntitlementBasicPing
=== CONT  TestAccEntitlementScriptBasic
=== CONT  TestAccApplianceConnector
=== CONT  TestAccApplianceBasicController
=== CONT  TestAccDeviceScriptBasic
=== CONT  TestAccTrustedCertificateBasic
=== CONT  TestAccApplianceCustomizationBasic
=== CONT  TestAccSiteBasicAwsResolverWithoutSecret
=== CONT  TestAccadministrativeRoleBasic
=== CONT  TestAccSiteBasic
=== CONT  TestAccAppgateTrustedCertificateDataSource
=== CONT  TestAccadministrativeMultiplePrivilegesValidation52
=== CONT  TestAccRingfenceRuleBasicTCP
=== CONT  TestAccAppgateMfaProviderDataSource
=== CONT  TestAccadministrativeMultiplePrivilegesValidation
=== CONT  TestAccRingfenceRuleBasicICMP
=== CONT  TestAccAppgateApplianceCustomizationDataSource
=== CONT  TestAccadministrativeRoleWithScope
=== CONT  TestAccPolicyBasic
=== CONT  TestAccadministrativeMultiplePrivilegesValidation52
    resource_appgate_administrative_role_test.go:264: Test is only for 5.2, privileges.target OnBoardedDevice
--- SKIP: TestAccadministrativeMultiplePrivilegesValidation52 (2.19s)
=== CONT  TestAccLdapCertificateIdentityProvidervBasic
--- PASS: TestAccAppgateMfaProviderDataSource (9.26s)
=== CONT  TestAccAdminMfaSettingsBasic
--- PASS: TestAccAppgateTrustedCertificateDataSource (9.40s)
=== CONT  TestAccMfaProviderBasic
--- PASS: TestAccAppgateAdministrativeRoleDataSource (9.67s)
=== CONT  TestAccLocalUserBasic
--- PASS: TestAccAppgateApplianceCustomizationDataSource (9.73s)
=== CONT  TestAccIPPoolBasic
--- PASS: TestAccRingfenceRuleBasicTCP (10.73s)
=== CONT  TestAccSamlIdentityProviderBasic
--- PASS: TestAccSiteBasicAwsResolverWithoutSecret (11.28s)
=== CONT  TestAccRadiusIdentityProviderBasic
--- PASS: TestAccadministrativeRoleBasic (11.33s)
=== CONT  TestAccLdapIdentityProviderBasic
--- PASS: TestAccDeviceScriptBasic (11.45s)
=== CONT  TestAccBlacklistUserBasic
--- PASS: TestAccPolicyBasic (11.61s)
=== CONT  TestAccCriteriaScriptBasic
--- PASS: TestAccRingfenceRuleBasicICMP (11.66s)
=== CONT  TestAccConditionBasic
--- PASS: TestAccApplianceConnector (11.81s)
=== CONT  TestAccClientProfileBasic
--- PASS: TestAccTrustedCertificateBasic (12.05s)
=== CONT  TestAccApplianceBasicControllerOverriderSPADisabled
--- PASS: TestAccadministrativeRoleWithScope (12.14s)
=== CONT  TestAccAppliancePortalSetup
--- PASS: TestAccEntitlementScriptBasic (12.19s)
=== CONT  TestAccApplianceBasicControllerWithoutOverrideSPA
--- PASS: TestAccEntitlementBasicPing (12.52s)
=== CONT  TestAccApplianceBasicGateway
--- PASS: TestAccadministrativeMultiplePrivilegesValidation (12.77s)
=== CONT  TestAccEntitlementUpdateActionOrder
--- PASS: TestAccLdapCertificateIdentityProvidervBasic (11.80s)
=== CONT  TestAccGlobalSettingsBasic
--- PASS: TestAccApplianceCustomizationBasic (18.68s)
=== CONT  TestAccEntitlementUpdateActionPortsSetOrder
--- PASS: TestAccMfaProviderBasic (10.50s)
=== CONT  TestAccEntitlementUpdateActionHostOrder
--- PASS: TestAccAdminMfaSettingsBasic (11.64s)
=== CONT  TestAccEntitlementBasicWithMonitor
--- PASS: TestAccIPPoolBasic (11.27s)
--- PASS: TestAccLocalUserBasic (11.98s)
--- PASS: TestAccBlacklistUserBasic (11.17s)
--- PASS: TestAccCriteriaScriptBasic (11.47s)
--- PASS: TestAccLdapIdentityProviderBasic (11.79s)
--- PASS: TestAccConditionBasic (11.76s)
--- PASS: TestAccRadiusIdentityProviderBasic (12.48s)
--- PASS: TestAccApplianceBasicControllerOverriderSPADisabled (11.85s)
--- PASS: TestAccApplianceBasicGateway (11.63s)
--- PASS: TestAccApplianceBasicControllerWithoutOverrideSPA (12.12s)
--- PASS: TestAccGlobalSettingsBasic (10.43s)
--- PASS: TestAccSiteBasic (26.98s)
--- PASS: TestAccEntitlementUpdateActionOrder (15.65s)
--- PASS: TestAccApplianceBasicController (28.75s)
--- PASS: TestAccEntitlementUpdateActionPortsSetOrder (12.10s)
--- PASS: TestAccClientProfileBasic (19.20s)
--- PASS: TestAccAppliancePortalSetup (18.94s)
--- PASS: TestAccEntitlementUpdateActionHostOrder (11.51s)
--- PASS: TestAccEntitlementBasicWithMonitor (11.64s)
--- PASS: TestAccSamlIdentityProviderBasic (23.22s)
PASS
ok  	github.com/appgate/terraform-provider-appgatesdp/appgate	72.292s
```

</details>

<details>

tested on appliance 5.3.2-23587-release
```bash
> terraform version                                                                  
Terraform v1.0.2
on linux_amd64


> make testacc             
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./appgate -v -count 1 -parallel 20  -timeout 120m
=== RUN   TestNewClient
--- PASS: TestNewClient (0.00s)
=== RUN   TestLoginInternalServerError
--- PASS: TestLoginInternalServerError (0.00s)
=== RUN   TestConfig
=== RUN   TestConfig/test_before_5.4
=== RUN   TestConfig/test_5.4_login
=== RUN   TestConfig/invalid_client_version
--- PASS: TestConfig (0.01s)
    --- PASS: TestConfig/test_before_5.4 (0.00s)
    --- PASS: TestConfig/test_5.4_login (0.00s)
    --- PASS: TestConfig/invalid_client_version (0.00s)
=== RUN   TestAccAppgateAdministrativeRoleDataSource
=== PAUSE TestAccAppgateAdministrativeRoleDataSource
=== RUN   TestAccAppgateApplianceCustomizationDataSource
=== PAUSE TestAccAppgateApplianceCustomizationDataSource
=== RUN   TestAccAppgateApplianceSeedDataSource
--- PASS: TestAccAppgateApplianceSeedDataSource (13.49s)
=== RUN   TestAccAppgateCADataSource
--- PASS: TestAccAppgateCADataSource (2.48s)
=== RUN   TestAccAppgateGlobalSettingsDataSource
--- PASS: TestAccAppgateGlobalSettingsDataSource (2.46s)
=== RUN   TestAccAppgateIdentityProviderDataSource
--- PASS: TestAccAppgateIdentityProviderDataSource (2.56s)
=== RUN   TestAccAppgateIPPoolDataSource
--- PASS: TestAccAppgateIPPoolDataSource (3.24s)
=== RUN   TestAccAppgateLocalUserDataSource
--- PASS: TestAccAppgateLocalUserDataSource (3.22s)
=== RUN   TestAccAppgateMfaProviderDataSource
=== PAUSE TestAccAppgateMfaProviderDataSource
=== RUN   TestAccAppgateTrustedCertificateDataSource
=== PAUSE TestAccAppgateTrustedCertificateDataSource
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestAccadministrativeRoleBasic
=== PAUSE TestAccadministrativeRoleBasic
=== RUN   TestAccadministrativeRoleWithScope
=== PAUSE TestAccadministrativeRoleWithScope
=== RUN   TestAccadministrativeMultiplePrivilegesValidation
=== PAUSE TestAccadministrativeMultiplePrivilegesValidation
=== RUN   TestAccadministrativeMultiplePrivilegesValidation52
=== PAUSE TestAccadministrativeMultiplePrivilegesValidation52
=== RUN   TestAccApplianceCustomizationBasic
=== PAUSE TestAccApplianceCustomizationBasic
=== RUN   TestAccApplianceBasicController
=== PAUSE TestAccApplianceBasicController
=== RUN   TestAccApplianceConnector
=== PAUSE TestAccApplianceConnector
=== RUN   TestAccApplianceBasicGateway
=== PAUSE TestAccApplianceBasicGateway
=== RUN   TestAccApplianceBasicControllerWithoutOverrideSPA
=== PAUSE TestAccApplianceBasicControllerWithoutOverrideSPA
=== RUN   TestAccApplianceBasicControllerOverriderSPADisabled
=== PAUSE TestAccApplianceBasicControllerOverriderSPADisabled
=== RUN   TestAccAppliancePortalSetup
=== PAUSE TestAccAppliancePortalSetup
=== RUN   TestAccBlacklistUserBasic
=== PAUSE TestAccBlacklistUserBasic
=== RUN   TestAccClientConnectionsBasic
--- PASS: TestAccClientConnectionsBasic (3.71s)
=== RUN   TestAccClientProfileBasic
=== PAUSE TestAccClientProfileBasic
=== RUN   TestAccConditionBasic
=== PAUSE TestAccConditionBasic
=== RUN   TestAccCriteriaScriptBasic
=== PAUSE TestAccCriteriaScriptBasic
=== RUN   TestAccDeviceScriptBasic
=== PAUSE TestAccDeviceScriptBasic
=== RUN   TestAccEntitlementScriptBasic
=== PAUSE TestAccEntitlementScriptBasic
=== RUN   TestAccEntitlementBasicPing
=== PAUSE TestAccEntitlementBasicPing
=== RUN   TestAccEntitlementBasicWithMonitor
=== PAUSE TestAccEntitlementBasicWithMonitor
=== RUN   TestAccEntitlementUpdateActionOrder
=== PAUSE TestAccEntitlementUpdateActionOrder
=== RUN   TestAccEntitlementUpdateActionHostOrder
=== PAUSE TestAccEntitlementUpdateActionHostOrder
=== RUN   TestAccEntitlementUpdateActionPortsSetOrder
=== PAUSE TestAccEntitlementUpdateActionPortsSetOrder
=== RUN   TestAccGlobalSettingsBasic
=== PAUSE TestAccGlobalSettingsBasic
=== RUN   TestAccConnectorIdentityProviderBasic
--- PASS: TestAccConnectorIdentityProviderBasic (4.05s)
=== RUN   TestAccLdapCertificateIdentityProvidervBasic
=== PAUSE TestAccLdapCertificateIdentityProvidervBasic
=== RUN   TestAccLdapIdentityProviderBasic
=== PAUSE TestAccLdapIdentityProviderBasic
=== RUN   TestAccLocalDatabaseIdentityProviderBasic
--- PASS: TestAccLocalDatabaseIdentityProviderBasic (4.05s)
=== RUN   TestAccRadiusIdentityProviderBasic
=== PAUSE TestAccRadiusIdentityProviderBasic
=== RUN   TestAccSamlIdentityProviderBasic
=== PAUSE TestAccSamlIdentityProviderBasic
=== RUN   TestAccIPPoolBasic
=== PAUSE TestAccIPPoolBasic
=== RUN   TestAccLocalUserBasic
=== PAUSE TestAccLocalUserBasic
=== RUN   TestAccMfaProviderBasic
=== PAUSE TestAccMfaProviderBasic
=== RUN   TestAccAdminMfaSettingsBasic
=== PAUSE TestAccAdminMfaSettingsBasic
=== RUN   TestAccPolicyBasic
=== PAUSE TestAccPolicyBasic
=== RUN   TestAccRingfenceRuleBasicICMP
=== PAUSE TestAccRingfenceRuleBasicICMP
=== RUN   TestAccRingfenceRuleBasicTCP
=== PAUSE TestAccRingfenceRuleBasicTCP
=== RUN   TestAccSiteBasic
=== PAUSE TestAccSiteBasic
=== RUN   TestAccSiteBasicAwsResolverWithoutSecret
=== PAUSE TestAccSiteBasicAwsResolverWithoutSecret
=== RUN   TestAccTrustedCertificateBasic
=== PAUSE TestAccTrustedCertificateBasic
=== CONT  TestAccAppgateAdministrativeRoleDataSource
=== CONT  TestAccEntitlementBasicPing
=== CONT  TestAccApplianceBasicGateway
=== CONT  TestAccEntitlementScriptBasic
=== CONT  TestAccSiteBasic
=== CONT  TestAccDeviceScriptBasic
=== CONT  TestAccRingfenceRuleBasicTCP
=== CONT  TestAccCriteriaScriptBasic
=== CONT  TestAccRingfenceRuleBasicICMP
=== CONT  TestAccConditionBasic
=== CONT  TestAccLocalUserBasic
=== CONT  TestAccClientProfileBasic
=== CONT  TestAccTrustedCertificateBasic
=== CONT  TestAccPolicyBasic
=== CONT  TestAccSiteBasicAwsResolverWithoutSecret
=== CONT  TestAccIPPoolBasic
=== CONT  TestAccAdminMfaSettingsBasic
=== CONT  TestAccMfaProviderBasic
=== CONT  TestAccSamlIdentityProviderBasic
=== CONT  TestAccRadiusIdentityProviderBasic
--- PASS: TestAccAppgateAdministrativeRoleDataSource (9.47s)
=== CONT  TestAccLdapIdentityProviderBasic
--- PASS: TestAccRingfenceRuleBasicTCP (10.53s)
=== CONT  TestAccLdapCertificateIdentityProvidervBasic
--- PASS: TestAccTrustedCertificateBasic (10.82s)
=== CONT  TestAccGlobalSettingsBasic
--- PASS: TestAccDeviceScriptBasic (10.87s)
=== CONT  TestAccEntitlementUpdateActionPortsSetOrder
--- PASS: TestAccLocalUserBasic (11.00s)
=== CONT  TestAccEntitlementUpdateActionHostOrder
--- PASS: TestAccRingfenceRuleBasicICMP (11.23s)
=== CONT  TestAccEntitlementUpdateActionOrder
--- PASS: TestAccPolicyBasic (11.28s)
=== CONT  TestAccEntitlementBasicWithMonitor
--- PASS: TestAccEntitlementScriptBasic (11.52s)
=== CONT  TestAccApplianceBasicControllerOverriderSPADisabled
--- PASS: TestAccCriteriaScriptBasic (11.61s)
=== CONT  TestAccBlacklistUserBasic
--- PASS: TestAccAdminMfaSettingsBasic (11.79s)
=== CONT  TestAccAppliancePortalSetup
--- PASS: TestAccMfaProviderBasic (11.93s)
=== CONT  TestAccadministrativeMultiplePrivilegesValidation
--- PASS: TestAccConditionBasic (12.10s)
=== CONT  TestAccApplianceConnector
--- PASS: TestAccIPPoolBasic (12.12s)
=== CONT  TestAccApplianceBasicController
--- PASS: TestAccSiteBasicAwsResolverWithoutSecret (12.33s)
=== CONT  TestAccApplianceCustomizationBasic
--- PASS: TestAccApplianceBasicGateway (12.41s)
=== CONT  TestAccadministrativeMultiplePrivilegesValidation52
--- PASS: TestAccEntitlementBasicPing (12.71s)
=== CONT  TestAccApplianceBasicControllerWithoutOverrideSPA
--- PASS: TestAccRadiusIdentityProviderBasic (12.81s)
=== CONT  TestAccadministrativeRoleWithScope
=== CONT  TestAccAppliancePortalSetup
    resource_appgate_appliance_test.go:2161: Test only for 5.4 and above, appliance.portal is only supported in 5.4 and above.
=== CONT  TestAccadministrativeMultiplePrivilegesValidation52
    resource_appgate_administrative_role_test.go:264: Test is only for 5.2, privileges.target OnBoardedDevice
--- SKIP: TestAccAppliancePortalSetup (1.82s)
=== CONT  TestAccadministrativeRoleBasic
--- SKIP: TestAccadministrativeMultiplePrivilegesValidation52 (1.50s)
=== CONT  TestAccAppgateTrustedCertificateDataSource
--- PASS: TestAccLdapIdentityProviderBasic (12.34s)
=== CONT  TestAccAppgateMfaProviderDataSource
--- PASS: TestAccAppgateTrustedCertificateDataSource (9.02s)
=== CONT  TestAccAppgateApplianceCustomizationDataSource
--- PASS: TestAccBlacklistUserBasic (11.40s)
--- PASS: TestAccLdapCertificateIdentityProvidervBasic (12.61s)
--- PASS: TestAccadministrativeMultiplePrivilegesValidation (11.49s)
--- PASS: TestAccGlobalSettingsBasic (12.87s)
--- PASS: TestAccApplianceBasicControllerOverriderSPADisabled (12.50s)
--- PASS: TestAccApplianceConnector (12.50s)
--- PASS: TestAccadministrativeRoleBasic (11.27s)
--- PASS: TestAccadministrativeRoleWithScope (12.23s)
--- PASS: TestAccApplianceBasicControllerWithoutOverrideSPA (12.39s)
--- PASS: TestAccSiteBasic (27.59s)
--- PASS: TestAccApplianceCustomizationBasic (15.71s)
--- PASS: TestAccEntitlementUpdateActionPortsSetOrder (17.43s)
--- PASS: TestAccAppgateMfaProviderDataSource (6.73s)
--- PASS: TestAccEntitlementUpdateActionHostOrder (17.88s)
--- PASS: TestAccEntitlementUpdateActionOrder (17.95s)
--- PASS: TestAccAppgateApplianceCustomizationDataSource (6.35s)
--- PASS: TestAccEntitlementBasicWithMonitor (18.44s)
--- PASS: TestAccSamlIdentityProviderBasic (30.26s)
--- PASS: TestAccApplianceBasicController (21.11s)
--- PASS: TestAccClientProfileBasic (53.33s)
PASS
ok  	github.com/appgate/terraform-provider-appgatesdp/appgate	92.615s
```

</details>

### CODE REVIEW

File: appgate/provider.go [hunk 1]
```diff
@@ -129,50 +129,71 @@ func Provider() *schema.Provider {
...
-				Summary:  fmt.Sprintf("You are using old version of Appgate SDP SDK client v%d", v),
-				Detail:   "You are using an outdated version of appgate appliances, you should consider updating to the latest version.",
-			})
-		}
-		log.Printf("[INFO] Appgate SDP Appliance Version %q client version v%d", c.ApplianceVersion, c.ClientVersion)
-		return c, diags
+	if !requiredParameters(d) {
+		diags = append(diags, diag.Diagnostic{
+			Severity: diag.Error,
+			Summary:  "Missing appgate SDP credentials",
```
Comment (natan-abolafya) [inline appgate/provider.go:153]:
```suggestion
			Summary:  "Missing Appgate SDP credentials",
```

**Review by natan-abolafya — APPROVED** [review]
looks good to me
